<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin Panel' => 'Панель админа',
    'Articles' => 'Статьи',
    'Back to Application' => 'Назад в приложение',
    'Back to Home Page' => 'На главную',
    'Categories' => 'Категории',
    'Comments' => 'Комментарии',
    'Continue Reading' => 'Читать полностью',
    'Email' => 'Эл. почта',
    'Home' => 'Главная',
    'Incorrect email or password.' => 'Введена неверная эл. почта или пароль.',
    'Leave a Reply' => 'Ответить',
    'Login' => 'Войти',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Photo' => 'Фото',
    'Please fill out the following fields to login:' => 'Пожалуйста, заполните следующие поля для входа:',
    'Popular Posts' => 'Популярные посты',
    'Post Comment' => 'Оставить комментарий',
    'Recent Posts' => 'Недавние посты',
    'Register' => 'Регистрация',
    'Reply' => 'Ответ',
    'Sorry, we could not found the page you are looking for!' => 'Извините, мы не смогли найти у себя такую страницу!',
    'Tags' => 'Теги',
    'Treasure | A Blog About Travelling' => 'Treasure | Блог о путешествиях',
    'View Post' => 'Читать пост',
    'Write Message' => 'Написать сообщение',
    'Your comment will be added soon!' => 'Ваш комментарий скоро добавится!',
    'By %s On %s' => 'Автор: %s, добавлено: %s',
    'Logout' => 'Выйти',
    'Sign Up' => 'Регистрация',
];
